### ISSUE TITLE
dev-haskell/megaparsec-9.5.0 Warning: Couldn't figure out C compiler information! Make sure you're using GNU gcc, or clang

### ISSUE THREAD

**Issue by formula-spectre** [gentoo-haskell/gentoo-haskell#1503] opened 2023-11-20 19:52 UTC
```
 * Package:    dev-haskell/megaparsec-9.5.0:0/9.5.0
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_musl kernel_linux profile
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking megaparsec-9.5.0.tar.gz to /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work
>>> Unpacking megaparsec-9.5.0-rev4.cabal to /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work
unpack megaparsec-9.5.0-rev4.cabal: file format not recognized. Ignoring.
>>> Source unpacked in /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work
>>> Preparing source in /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0 ...
 * Using revised .cabal file from Hackage: revision 4
dos2unix: converting file /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/megaparsec.cabal to Unix format...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0 ...
 * Using cabal-3.6.3.0.
/usr/bin/ghc -hide-all-packages -package Cabal -package array -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml --make /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.hs -j4 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.hs, /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.o )

<no location info>: error:
    Warning: Couldn't figure out C compiler information!
             Make sure you're using GNU gcc, or clang

<no location info>: error:
    ghc: could not execute: x86_64-gentoo-linux-musl-clang-16
/usr/bin/ghc -hide-all-packages -package Cabal -package array -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml --make /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.hs -j4 +RTS -A256M -qb0 -RTS -threaded -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.hs, /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.o )

<no location info>: error:
    Warning: Couldn't figure out C compiler information!
             Make sure you're using GNU gcc, or clang

<no location info>: error:
    ghc: could not execute: x86_64-gentoo-linux-musl-clang-16
 * ERROR: dev-haskell/megaparsec-9.5.0::haskell failed (configure phase):
 *   compiling /var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0/Setup.hs failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 2032:  Called haskell-cabal_src_configure '--flag=-dev'
 *   environment, line 1689:  Called cabal-bootstrap
 *   environment, line  542:  Called die
 * The specific snippet of code:
 *           } || make_setup "$@" || die "compiling ${setupmodule} failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/megaparsec-9.5.0::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/megaparsec-9.5.0::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/megaparsec-9.5.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/megaparsec-9.5.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0'
 * S: '/var/tmp/portage/dev-haskell/megaparsec-9.5.0/work/megaparsec-9.5.0'

```
[emerge --info](https://github.com/gentoo-haskell/gentoo-haskell/files/13418846/emerge-info.txt)
let me know if anything else is needed!
one thing to note is that it says `x86_64-gentoo-linux-musl-clang-16`, while `clang --version` says `17.0.5`..

**Comment by hololeap** [comment] 2023-11-23 18:31
Duplicate of #1504

**Closed by hololeap** 2023-11-23 18:31 UTC
