### ISSUE TITLE
dev-haskell/hlint-2.1.15: No instance for (Brackets Exp_)

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1057] opened 2020-04-26 17:23 UTC
```
[ 2 of 53] Compiling HSE.Util         ( src/HSE/Util.hs, dist/build/HSE/Util.o )

src/HSE/Util.hs:206:19: error:
    • No instance for (Brackets Exp_)
        arising from a use of ‘needBracket’
      There are instances for similar types:
        instance (Data l, Default l) =>
                 Brackets
                   (haskell-src-exts-1.20.3:Language.Haskell.Exts.Syntax.Exp l)
          -- Defined in ‘haskell-src-exts-util-0.2.5:Language.Haskell.Exts.Bracket’
    • In the expression: needBracket i parent child
      In an equation for ‘needBracketOld’:
          needBracketOld i parent child
            | isDotApp parent, isDotApp child, i == 1 = False
            | otherwise = needBracket i parent child
    |
206 |     | otherwise = needBracket i parent child
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/HSE/Util.hs:222:50: error:
    • No instance for (Brackets (Exp S))
        arising from a use of ‘addParen’
      There are instances for similar types:
        instance (Data l, Default l) =>
                 Brackets
                   (haskell-src-exts-1.20.3:Language.Haskell.Exts.Syntax.Exp l)
          -- Defined in ‘haskell-src-exts-util-0.2.5:Language.Haskell.Exts.Bracket’
    • In the expression: addParen y
      In an equation for ‘f’: f i y | needBracketOld i x y = addParen y
      In an equation for ‘descendBracketOld’:
          descendBracketOld op x
            = descendIndex g x
            where
                g i y
                  = if a then f i b else b
                  where
                      (a, b) = op y
                f i (Paren _ y) | not $ needBracketOld i x y = y
                f i y | needBracketOld i x y = addParen y
                f _ y = y
    |
222 |         f i y           | needBracketOld i x y = addParen y
    |                                                  ^^^^^^^^^^

src/HSE/Util.hs:340:6: error:
    • No instance for (Default SrcSpanInfo) arising from a use of ‘def’
      There are instances for similar types:
        instance Default
                   haskell-src-exts-1.20.3:Language.Haskell.Exts.SrcLoc.SrcSpanInfo
          -- Defined in ‘Language.Haskell.Exts.Util’
    • In the expression: def
      In an equation for ‘an’: an = def
    |
340 | an = def
    |      ^^^
```

**Comment by solpeth** [comment] 2020-04-27 01:24
I can't reproduce this. Could you attach the full build log?

**Comment by l29ah** [comment] 2020-04-27 11:18
[build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/4539243/build.log)

**Comment by solpeth** [comment] 2020-04-27 20:52
I'm still feeling like `haskell-src-exts-util` has been built against `haskell-src-exts-1.20.3`. Is that possible?

What happens when you rebuild `haskell-src-exts-util` manually?

If so, this needs to be flagged to Portage. One possibility is artificially bumping the dependency bounds on `haskell-src-exts`, in each depending package, to its highest possible bounds.

**Comment by l29ah** [comment] 2020-04-27 22:55
On Mon, Apr 27, 2020 at 01:52:57PM -0700, Jack Todaro wrote:
> What happens when you rebuild `haskell-src-exts-util` manually?

No effect.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by solpeth** [comment] 2020-04-28 01:00
I'm not sure then, at this stage. I'll have a think.

Like I said, I cannot reproduce this at this time.

**Comment by l29ah** [comment] 2020-06-30 13:07
Same thing with 2.1.17. Fixed by removing dev-haskell/haskell-src-exts:1.22

**Comment by solpeth** [comment] 2020-07-09 22:04
Closing since you've said it's fixed for you. Feel free to reopen if the issue otherwise persists.

**Closed by solpeth** 2020-07-09 22:04 UTC
