### ISSUE TITLE
Cross compilation and strip

### ISSUE THREAD

**Issue by InBetweenNames** [gentoo-haskell/gentoo-haskell#960] opened 2019-08-29 23:32 UTC
So GHC 8.8.1 is able to build as a cross compiler for ARM at least (yay!) but Portage wants to apply the host binutils `strip` utility to all static archives in ghc before merging it into the system.  This results in the following output from strip:

~~~
x86_64-pc-linux-gnu-strip: Unable to recognise the format of the input file `/tmp/portage/cross-armv7a-hardfloat-linux-gnueabi/ghc-8.8.1/image/usr/lib64/armv7a-hardfloat-linux-gnueabi-ghc-8.8.1/rts/libHSrts_l.a(Disassembler.l_o)'
x86_64-pc-linux-gnu-strip: Unable to recognise the format of the input file `/tmp/portage/cross-armv7a-hardfloat-linux-gnueabi/ghc-8.8.1/image/usr/lib64/armv7a-hardfloat-linux-gnueabi-ghc-8.8.1/rts/libHSrts_thr.a(BlockAlloc.thr_o)'
...
~~~

Here, you can see that `x86_64-pc-linux-gnu-strip` is being applied to static archives that are cross compiled as `armv7a-hardfloat-linux-gnueabi`.  Strip actually mangles these archives as a result and this creates linking errors anytime you try to produce an executable with GHC.  You will see something very similar to the following if you examine any of the installed static archives in your system:

~~~
libHSdirectory-1.3.3.24/C_utimensat.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Common.o:      ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Config.o:      ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Directory.o:   ELF 32-bit LSB relocatable, no machine, version 1 (SYSV), stripped
libHSdirectory-1.3.3.24/Internal.o:    ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Posix.o:       ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Prelude.o:     ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
libHSdirectory-1.3.3.24/Windows.o:     ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
~~~

The `no machine` architecture for `Directory.o` is what causes the linking error.  Before stripping with the wrong utility, this archive was perfectly fine.

Since the GHC ebuilds are `EAPI=6`, this can be worked around with a simple `STRIP_MASK="*.a"` in the ebuild, however for EAPI 7 this will require a little more nuance as `STRIP_MASK` is banned and the exact path that the cross compiled libraries reside in must be passed to `dostrip -x`.  I notice that the official `toolchain.eclass` uses `RESTRICT=strip`, but it's not clear to me if this is allowed in EAPI 7 or not.

This isn't the first time I've been burned by this behavior in Portage (we dealt with it in GentooLTO as well).  Unfortunately, unlike with what we found over at GentooLTO, this can't be fixed with a subsequent `ranlib`.

How do you think we could best prevent this from happening in cross compiled builds of GHC?

**Comment by trofi** [comment] 2019-08-30 06:32
ghc should be fixed to call the correct strip. I never saw the problem because I am running sys-devel/binutils[multitarget]. Please attach full build.log if possible. I'll try to reproduce locally and run basic tests.

**Comment by InBetweenNames** [comment] 2019-08-30 13:56
It's not GHC that's at fault.  GHC does call the correct strip.  The ebuild removes `STRIP_CMD` from GHC for other reasons.  It's portage itself, as part of the `dostrip` functionality, that is calling the host strip on the cross compiled static archives.  I can prove this by adding `RESTRICT=strip` to `cross-*/ghc` and observing that this problem goes away.

Note that `toolchain.eclass` does the same thing.

You will only be able to observe the problem if you try to link an executable with GHC -- it won't be able to recognize the mangled static archives.

**Comment by trofi** [comment] 2019-08-30 18:50
Yes, that makes sense. I still would like to see `emerge --info` and `build.log`.

**Closed** 2019-08-31 18:10 UTC

**Comment by InBetweenNames** [comment] 2019-08-31 23:55
Thank you!
