### ISSUE TITLE
Error building skylighting-core-0.13.2 -- ghc: panic

### ISSUE THREAD

**Issue by hereGittyGitty** [gentoo-haskell/gentoo-haskell#1401] opened 2023-03-25 16:31 UTC
Hi,

I am having problems building _dev-haskell/skylighting-core-0.13.2_. It fails with the following error:
```
>>> Compiling source in /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2 ...
./setup build
Preprocessing library for skylighting-core-0.13.2..
Building library for skylighting-core-0.13.2..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.7:
	ModOrigin: hidden module redefined
  x: unusable module
  y: unusable module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

 * ERROR: dev-haskell/skylighting-core-0.13.2::haskell failed (compile phase):
 *   setup build failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 1947:  Called haskell-cabal_src_compile
 *   environment, line 1605:  Called cabal_src_compile
 *   environment, line  801:  Called cabal-build
 *   environment, line  524:  Called die
 * The specific snippet of code:
 *       ./setup "$@" || die "setup build failed"
```

Here is my complete build log:

```
 * Package:    dev-haskell/skylighting-core-0.13.2:0/0.13.2
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc hoogle hscolour kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking skylighting-core-0.13.2.tar.gz to /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work
>>> Source unpacked in /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work
>>> Preparing source in /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2 ...
dos2unix: converting file /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2/skylighting-core.cabal to Unix format...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2 ...
 * Using cabal-3.6.3.0.
/usr/bin/ghc -hide-all-packages -package Cabal -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml --make /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2/Setup.hs -j9 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2/Setup.hs, /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2/Setup.o )
Linking setup ...
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=skylighting-core-0.13.2/ghc-9.2.7 --datadir=/usr/share/ --datasubdir=skylighting-core-0.13.2/ghc-9.2.7 --disable-tests --ghc-options=-j9 +RTS -A256M -qb0 -RTS --with-ar=x86_64-pc-linux-gnu-ar --ghc-option=-optc-march=skylake --ghc-option=-optc-mtune=skylake --ghc-option=-optc-O2 --ghc-option=-optc-pipe --ghc-option=-optc-frecord-gcc-switches --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --disable-executable-stripping --docdir=/usr/share/doc/skylighting-core-0.13.2 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping --flags=-executable --flag=system-pcre
Using Parsec parser
Configuring skylighting-core-0.13.2...
Flags chosen: executable=False
Dependency aeson >=1.0: using aeson-2.0.3.0
Dependency attoparsec: using attoparsec-0.14.4
Dependency base >=4.8 && <5.0: using base-4.16.4.0
Dependency base64-bytestring: using base64-bytestring-1.2.1.0
Dependency binary: using binary-0.8.9.0
Dependency bytestring: using bytestring-0.11.4.0
Dependency case-insensitive: using case-insensitive-1.2.1.0
Dependency colour >=2.0: using colour-2.3.6
Dependency containers >=0.6.0.1: using containers-0.6.5.1
Dependency directory >=1.2.5: using directory-1.3.6.2
Dependency filepath: using filepath-1.4.2.2
Dependency mtl: using mtl-2.2.2
Dependency safe: using safe-0.3.19
Dependency text: using text-1.2.5.0
Dependency transformers: using transformers-0.5.6.2
Dependency utf8-string: using utf8-string-1.0.2
Dependency xml-conduit >=1.9.1.0 && <1.10: using xml-conduit-1.9.1.2
Source component graph: component lib
Configured component graph:
    component skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i
        include aeson-2.0.3.0-KJu5qowkwwHI4bXEPjKFDf
        include attoparsec-0.14.4-HZrjNhRdlHF8e0sw2UGqZ3
        include base-4.16.4.0
        include base64-bytestring-1.2.1.0-APmD3ny5xOU8uSlwgDmyWU
        include binary-0.8.9.0
        include bytestring-0.11.4.0
        include case-insensitive-1.2.1.0-GjXWX2FMVvK6BRyYjbvLax
        include colour-2.3.6-9Flkk1pUiR57nwp1ltUbyz
        include containers-0.6.5.1
        include directory-1.3.6.2
        include filepath-1.4.2.2
        include mtl-2.2.2
        include safe-0.3.19-3Atv9xv1FTZE5WsEtdRBSd
        include text-1.2.5.0
        include transformers-0.5.6.2
        include utf8-string-1.0.2-KOPUXETbFeRLoWT9IcwQzV
        include xml-conduit-1.9.1.2-HY23pSMZjUwFFxBVAmFNbQ
Linked component graph:
    unit skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i
        include aeson-2.0.3.0-KJu5qowkwwHI4bXEPjKFDf
        include attoparsec-0.14.4-HZrjNhRdlHF8e0sw2UGqZ3
        include base-4.16.4.0
        include base64-bytestring-1.2.1.0-APmD3ny5xOU8uSlwgDmyWU
        include binary-0.8.9.0
        include bytestring-0.11.4.0
        include case-insensitive-1.2.1.0-GjXWX2FMVvK6BRyYjbvLax
        include colour-2.3.6-9Flkk1pUiR57nwp1ltUbyz
        include containers-0.6.5.1
        include directory-1.3.6.2
        include filepath-1.4.2.2
        include mtl-2.2.2
        include safe-0.3.19-3Atv9xv1FTZE5WsEtdRBSd
        include text-1.2.5.0
        include transformers-0.5.6.2
        include utf8-string-1.0.2-KOPUXETbFeRLoWT9IcwQzV
        include xml-conduit-1.9.1.2-HY23pSMZjUwFFxBVAmFNbQ
        Skylighting.Core=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Core,Skylighting.Loader=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Loader,Skylighting.Parser=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Parser,Skylighting.Regex=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Regex,Skylighting.Styles=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Styles,Skylighting.Tokenizer=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Tokenizer,Skylighting.Types=skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i:Skylighting.Types
Ready component graph:
    definite skylighting-core-0.13.2-8T9MnzQAe7rIMV729etq5i
        depends aeson-2.0.3.0-KJu5qowkwwHI4bXEPjKFDf
        depends attoparsec-0.14.4-HZrjNhRdlHF8e0sw2UGqZ3
        depends base-4.16.4.0
        depends base64-bytestring-1.2.1.0-APmD3ny5xOU8uSlwgDmyWU
        depends binary-0.8.9.0
        depends bytestring-0.11.4.0
        depends case-insensitive-1.2.1.0-GjXWX2FMVvK6BRyYjbvLax
        depends colour-2.3.6-9Flkk1pUiR57nwp1ltUbyz
        depends containers-0.6.5.1
        depends directory-1.3.6.2
        depends filepath-1.4.2.2
        depends mtl-2.2.2
        depends safe-0.3.19-3Atv9xv1FTZE5WsEtdRBSd
        depends text-1.2.5.0
        depends transformers-0.5.6.2
        depends utf8-string-1.0.2-KOPUXETbFeRLoWT9IcwQzV
        depends xml-conduit-1.9.1.2-HY23pSMZjUwFFxBVAmFNbQ
Using Cabal-3.6.3.0 compiled by ghc-9.2
Using compiler: ghc-9.2.7
Using install prefix: /usr
Executables installed in: /usr/bin
Libraries installed in: /usr/lib64/skylighting-core-0.13.2/ghc-9.2.7
Dynamic Libraries installed in: /usr/lib64/x86_64-linux-ghc-9.2.7
Private executables installed in:
/usr/libexec/x86_64-linux-ghc-9.2.7/skylighting-core-0.13.2
Data files installed in: /usr/share/skylighting-core-0.13.2/ghc-9.2.7
Documentation installed in: /usr/share/doc/skylighting-core-0.13.2
Configuration files installed in: /etc
Using alex version 3.2.7.1 found on system at: /usr/bin/alex
Using ar given by user at: /usr/bin/x86_64-pc-linux-gnu-ar
Using c2hs version 0.28.8 found on system at: /usr/bin/c2hs
Using cpphs version 1.20.9 found on system at: /usr/bin/cpphs
No doctest found
Using gcc version 12 found on system at: /usr/bin/x86_64-pc-linux-gnu-gcc
Using ghc version 9.2.7 given by user at: /usr/bin/ghc
Using ghc-pkg version 9.2.7 given by user at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.26.0 found on system at: /usr/bin/haddock-ghc-9.2.7
Using happy version 1.20.0 found on system at: /usr/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.68 found on system at: /usr/bin/hpc
Using hsc2hs version 0.68.8 found on system at: /usr/bin/hsc2hs
Using hscolour version 1.24 found on system at: /usr/bin/HsColour
No jhc found
Using ld found on system at: /usr/bin/x86_64-pc-linux-gnu-ld
Using pkg-config version 1.8.1 found on system at: /usr/bin/pkg-config
Using runghc version 9.2.7 found on system at: /usr/bin/runghc-9.2.7
Using strip version 2.39 found on system at: /usr/bin/strip
Using tar found on system at: /usr/bin/tar
No uhc found
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2 ...
./setup build
Preprocessing library for skylighting-core-0.13.2..
Building library for skylighting-core-0.13.2..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.7:
	ModOrigin: hidden module redefined
  x: unusable module
  y: unusable module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

 * ERROR: dev-haskell/skylighting-core-0.13.2::haskell failed (compile phase):
 *   setup build failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 1947:  Called haskell-cabal_src_compile
 *   environment, line 1605:  Called cabal_src_compile
 *   environment, line  801:  Called cabal-build
 *   environment, line  524:  Called die
 * The specific snippet of code:
 *       ./setup "$@" || die "setup build failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/skylighting-core-0.13.2::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/skylighting-core-0.13.2::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/skylighting-core-0.13.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/skylighting-core-0.13.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2'
 * S: '/var/tmp/portage/dev-haskell/skylighting-core-0.13.2/work/skylighting-core-0.13.2'
```

Here is my output of `emerge --info '=dev-haskell/skylighting-core-0.13.2::haskell'`

```
Portage 3.0.44 (python 3.10.10-final-0, default/linux/amd64/17.1/desktop/gnome/systemd/merged-usr, gcc-12, glibc-2.36-r7, 6.1.19-gentoo-x86_64 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-6.1.19-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-8565U_CPU_@_1.80GHz-with-glibc2.36
KiB Mem:    32670412 total,   8828988 free
KiB Swap:   49151996 total,  49151996 free
Timestamp of repository gentoo: Sat, 25 Mar 2023 10:00:01 +0000
Head commit of repository gentoo: d82071aeb9680f6af3dd35ac663172e927aa1c56
Timestamp of repository brother-overlay: Fri, 17 Mar 2023 22:18:40 +0000
Head commit of repository brother-overlay: 951c6423313475fb62d4a5985af43e7f999560e7

Timestamp of repository haskell: Sat, 25 Mar 2023 07:46:41 +0000
Head commit of repository haskell: 38441f4aae9735765394a103f012214e6eb60e21

Head commit of repository lolo-gcpan-overlay: 4e97e8b412c7edbaaebec1e62109a6c925bc99cd

Head commit of repository lolo-overlay: f92e99a9d058d6c8f50110b75c60b9b81c0d73fb

sh bash 5.1_p16-r2
ld GNU ld (Gentoo 2.39 p5) 2.39.0
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r2::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.36.0-r2::gentoo
dev-lang/python:           3.10.10_p3::gentoo, 3.11.2_p2::gentoo
dev-lang/rust:             1.66.1::gentoo
dev-util/cmake:            3.25.2::gentoo
dev-util/meson:            1.0.1::gentoo
sys-apps/baselayout:       2.13-r1::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-apps/systemd:          252.7::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r5::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.39-r4::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           14.0.6-r1::gentoo, 15.0.7-r1::gentoo
sys-devel/gcc:             12.2.1_p20230121-r1::gentoo
sys-devel/gcc-config:      2.8::gentoo
sys-devel/libtool:         2.4.7-r1::gentoo
sys-devel/lld:             15.0.7::gentoo
sys-devel/llvm:            14.0.6-r2::gentoo, 15.0.7::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  6.1::gentoo (virtual/os-headers)
sys-libs/glibc:            2.36-r7::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: True
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-max-age: 24

brother-overlay
    location: /var/db/repos/brother-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/brother-overlay.git
    masters: gentoo
    volatile: True

haskell
    location: /var/db/repos/haskell
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/haskell.git
    masters: gentoo
    volatile: True

lolo-gcpan-overlay
    location: /var/db/repos/lolo-gcpan-overlay
    sync-type: git
    sync-uri: https://github.com/hereGittyGitty/lolo-gcpan-overlay.git
    masters: gentoo
    volatile: True

lolo-overlay
    location: /var/db/repos/lolo-overlay
    sync-type: git
    sync-uri: https://github.com/hereGittyGitty/lolo-overlay.git
    masters: gentoo
    priority: 50
    volatile: True

Installed sets: @my_qt5-addons, @my_qt5-essentials, @my_qt5-tools
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE CC-Sampling-Plus-1.0"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -frecord-gcc-switches"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /opt/brother/scanner/brscan4/brsanenetdevice4.cfg /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/de/hunspell/ignore.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/de/hunspell/prohibited.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/de/hunspell/spelling.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/en/hunspell/ignore.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/en/hunspell/prohibited.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/en/hunspell/spelling.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/fr/hunspell/ignore.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/fr/hunspell/prohibited.txt /usr/share/languagetool/lib/language-modules/org/languagetool/resource/fr/hunspell/spelling.txt /usr/share/maven-bin-3.9/conf"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=skylake -mtune=skylake -O2 -pipe -frecord-gcc-switches"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-march=skylake -mtune=skylake -O2 -pipe -frecord-gcc-switches"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms split-elog strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=skylake -mtune=skylake -O2 -pipe -frecord-gcc-switches"
GENTOO_MIRRORS="https://gentoo.osuosl.org/ https://mirrors.rit.edu/gentoo/"
LANG="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LEX="flex"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X a52 aac acl acpi alsa amd64 bash-completion bluetooth branding bzip2 cairo cdda cdr cli colord crypt cups dbus dri dts dvd dvdr eds emacs encode evo exif flac fortran gdbm gif gnome gnome-keyring gnome-online-accounts gpm gstreamer gtk gui hoogle hscolour iconv icu introspection ipv6 jpeg lcms libglvnd libnotify libsecret libtirpc mad mng mp3 mp4 mpeg multilib nautilus ncurses networkmanager nls nptl offensive ogg opengl openmp pam pango pcre pdf png policykit ppds pulseaudio qt5 readline screencast sdl seccomp sound spell ssl startup-notification svg sysprof systemd test-rust tiff truetype udev udisks unicode upower usb vim-syntax vorbis wayland wxwidgets x264 xattr xcb xft xml xv xvid zlib zsh-completion" ABI_X86="64" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64 pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="de en fr" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1 lua5-4 luajit" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" RUBY_TARGETS="ruby27 ruby30" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, MAKEOPTS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

=================================================================
                        Package Settings
=================================================================

dev-haskell/skylighting-core-0.13.2::haskell was built with the following:
USE="hoogle hscolour -doc -executable -profile -test" ABI_X86="(64)"
FEATURES="sfperms qa-unresolved-soname-deps binpkg-logs userpriv unknown-features-warn binpkg-dostrip fixlafiles distlocks buildpkg-live usersync buildpkg pid-sandbox strict merge-sync xattr ipc-sandbox usersandbox ebuild-locks sandbox assume-digests split-elog userfetch parallel-fetch unmerge-logs protect-owned network-sandbox news binpkg-docompress multilib-strict unmerge-orphans config-protect-if-modified preserve-libs"
```

The output of `emerge -pqv '=dev-haskell/skylighting-core-0.13.2::haskell'`:

```
[ebuild   R   ] dev-haskell/skylighting-core-0.13.2  USE="hoogle hscolour -doc -executable -profile -test" 
```

thx

**Comment by solpeth** [comment] 2023-03-25 20:32
@hereGittyGitty workaround for now is `emerge -Cv skylighting-core && emerge -1v skylighting-core`.

Closing as duplicate of #1250 . A patch is being tested for ghc which should be pushed soon.

**Closed by solpeth** 2023-03-25 20:32 UTC
