### ISSUE TITLE
app-text/pandoc-2.9.2.1 requires a lot of RAM

### ISSUE THREAD

**Issue by ShimmerFairy** [gentoo-haskell/gentoo-haskell#1065] opened 2020-07-04 10:35 UTC
Before I installed the haskell overlay to get at some haskell packages not available in the main repo, pandoc-1.19.2.1-r1 (with ghc-8.0.2 and cabal-1.24.2.0) took only 7 minutes to compile on my system. But now, with ghc-8.8.3 and cabal-3.0.1.0, it takes up so much RAM that I cannot compile it, even when I set `MAKEOPTS` to `-j1` (it gets much farther before eating up all the RAM with a lower jobs number, but pandoc is just too big a project to beat the clock).

According to [this cabal issue](https://github.com/haskell/cabal/issues/6658) pandoc will require up to 6 GiB of RAM in the end (which is 2 more than my old 4 GiB system has), so the most recent pandoc ebuilds at least should check to see if you have that much and fail if you don't have enough.

I think the issue is with a newer ghc in general, for what it's worth, since I recall other packages eating up too much memory (though only pandoc's usage is unacceptable thus far). I'll mask the overlay's newer ghc ebuilds and hope for the best personally. (Worst case I just remove the overlay, get my system's haskell packages to a pre-overlay state, and install packages with `cabal` directly.)

**Comment by trofi** [comment] 2020-07-04 11:05
6GB sounds like a lot. Ideally we should track down the regression and report it upstream. ghc should be more eager at unloading unused modules, but it's a bit tricky to implement.

Meanwhile you can also try a crude workaround and use `HCFLAGS=-O0` on a few select heavyweight packages.

**Comment by solpeth** [comment] 2020-07-04 11:57
There is this at ghc upstream about `pandoc`: https://gitlab.haskell.org/ghc/ghc/-/issues/18010

`pandoc` is currently failing `hackage CI` due to overloading the build bots' memory requirements.

**Comment by ShimmerFairy** [comment] 2020-07-04 12:54
As I recall, for my usual `-j3` and on `-j2` the RAM overwhelming began on module 63, with `-j1` it made it as far as 101.

**Comment by solpeth** [comment] 2020-07-05 04:48
I'll muck around with `HCFLAGS` over the next few days to see if anything works. Assuming I find a solution I'm of the mind to enact it in the ebuild for all users (unless I play with checking for memory requirements), since this probably affects more than just us.

**Comment by solpeth** [comment] 2020-07-05 19:49
These are some of the upstream bug reports I found:

- [#13253](https://gitlab.haskell.org/ghc/ghc/-/issues/13253) (exponential compilation time)
- [#10421](https://gitlab.haskell.org/ghc/ghc/-/issues/10421) (exponential blowup in inlining)
- [#18223](https://gitlab.haskell.org/ghc/ghc/-/issues/18223) (simplifier uses gigabytes of memory)

In any case, as mentioned above by @trofi `HCFLAGS=-O0` works a treat.

**Comment by solpeth** [comment] 2020-07-05 20:47
Disabled optimisations in 8d8c6b63b270ce020bf39efb7b6fc5e8cad6d428. But I'll keep this open for the moment.

**Comment by solpeth** [comment] 2021-07-01 09:37
This appears to no longer be an issue at least on my machine (8GiB RAM) with ghc-8.10.5. Unless others are continuing to experience issues I'm tempted to finally re-enable optimisations by default.

Build time is still impacted, but memory isn't being aggressively exhausted like it used to.

**Comment by hololeap** [comment] 2021-08-10 02:46
This version isn't in the tree anymore, and the newest version with `ghc-8.10.5` doesn't seem to have this problem. Closing.

**Closed by hololeap** 2021-08-10 02:46 UTC
Labels: confirmed
