### ISSUE TITLE
dev-lang/elm-reactor and dev-lang/elm-compiler tries to download files in src_compile phase

### ISSUE THREAD

**Issue by graaff** [gentoo-haskell/gentoo-haskell#618] opened 2017-05-12 07:10 UTC
This is not allowed and may fail due to unavailability of a network,  e.g. when using FEATURES="network-sandbox". 

```
>>> Compiling source in /var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0 ...
./setup build
Building elm-reactor-0.18...
Preprocessing executable 'elm-reactor' for elm-reactor-0.18...
[1 of 8] Compiling StaticFiles.Build ( src/backend/StaticFiles/Build.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles/Build.dyn_o )
[2 of 8] Compiling Socket           ( src/backend/Socket.hs, dist/build/elm-reactor/elm-reactor-tmp/Socket.dyn_o )

src/backend/Socket.hs:15:11: Warning:
    Defined but not used: ‘watchedFile’
[3 of 8] Compiling Generate.Help    ( src/backend/Generate/Help.hs, dist/build/elm-reactor/elm-reactor-tmp/Generate/Help.dyn_o )
[4 of 8] Compiling StaticFiles      ( src/backend/StaticFiles.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles.dyn_o )
Failed to build src/pages/Errors.elm


Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18>

FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Name or service not known)
```

**Comment by solpeth** [comment] 2018-08-26 08:34
This also occurs in `dev-lang/elm-0.19.0`, which has merged `elm-reactor`.

**Comment by trofi** [comment] 2020-03-27 18:49
Yeah, we need to find a way to pull all dependencies via `SRC_URI`.

**Comment by ezzieyguywuf** [comment] 2020-12-23 02:29
I've narrowed down the issue to (these four lines)[https://github.com/elm/compiler/blob/0.19.1/terminal/src/Develop/StaticFiles/Build.hs#L44-L47] of code, at least for the `elm-compiler` package. I'm going to try to get help from upstream to figure out how to deal with this.

I can confirm that if the `reacter/elm-stuff` directory is provided to the build directory *ahead of time* (i simply copy/pasted it for the sakes of testing), that the build can then proceed just fine without network access.

The trick now is to find out *where* exactly these assets are fetched from, and then finding a way to fetch them in `SRC_URI`.

This is tricky b/c the final contents of the `reactor/elm-stuff` directory appear to be compiled "elm" stuff, so I have a feeling that what's being fetched is elm source code itself...

**Comment by ezzieyguywuf** [comment] 2020-12-23 03:26
[Issue filed](https://github.com/elm/compiler/issues/2160) upstream.

**Comment by ezzieyguywuf** [comment] 2020-12-25 02:15
@trofi if we're closing this bug, should we also mask the non-binary package, or leave it for those that don't mind disabling network-sandbox?

**Comment by trofi** [comment] 2020-12-25 22:59
This bug should not be closed. Probably github's handling of `not fix #N` comment was interpreted as `fix #N`.

**Comment by ezzieyguywuf** [comment] 2020-12-25 23:05
I agree, i didn't say anything because I thought you closed it on purpose.

**Comment by devurandom** [comment] 2021-04-13 19:03
Instead of waiting for a response to https://github.com/elm/compiler/issues/2160#issuecomment-776266926, can we include the extra files independently of the source tarball for now?

**Comment by ezzieyguywuf** [comment] 2021-04-14 15:29
@devurandom  absolutely, I would love to do this. I *think* that I need to add `https://github.com/${PN}/archive/${PV}.tar.gz` to SRC_URI, and the `cp` it to the appropriate place.

Unfortunately I have not had a chance to test this out or play around with it, as I've been focusing on other projects at the moment.

**Comment by trofi** [comment] 2021-07-04 10:52
Yeah, I think mechanically we can dump a bunch of files into a directory and point ELM_HOME at it.
A bit of cache structure has to be preserved. builder/src/Stuff.hs:getCacheDir:

```haskell
getReplCache :: IO FilePath
getReplCache =
  getCacheDir "repl"


getCacheDir :: FilePath -> IO FilePath
getCacheDir projectName =
  do  home <- getElmHome
      let root = home </> compilerVersion </> projectName
      Dir.createDirectoryIfMissing True root
      return root


getElmHome :: IO FilePath
getElmHome =
  do  maybeCustomHome <- Env.lookupEnv "ELM_HOME"
      case maybeCustomHome of
        Just customHome -> return customHome
        Nothing -> Dir.getAppUserDataDirectory "elm"
```

**Comment by trofi** [comment] 2021-07-04 11:40
Another hurdle: fetching depends files has to be done in a very specific way:

```
$ wget https://package.elm-lang.org/packages/elm/browser/1.0.1/elm.json
--2021-07-04 12:39:53--  https://package.elm-lang.org/packages/elm/browser/1.0.1/elm.json
Resolving package.elm-lang.org... 45.55.106.189
Connecting to package.elm-lang.org|45.55.106.189|:443... connected.
HTTP request sent, awaiting response... 406 Bad Accept-Encoding
2021-07-04 12:39:54 ERROR 406: Bad Accept-Encoding.

$ wget --compression=gzip -c https://package.elm-lang.org/packages/elm/browser/1.0.1/elm.json
Compression does not work with --continue or --start-pos, they will be disabled.
--2021-07-04 12:38:57--  https://package.elm-lang.org/packages/elm/browser/1.0.1/elm.json
Resolving package.elm-lang.org... 45.55.106.189
Connecting to package.elm-lang.org|45.55.106.189|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 294 [application/json]
Saving to: 'elm.json'

elm.json                 100%[==================================>]     294  --.-KB/s    in 0s

2021-07-04 12:38:57 (560 MB/s) - 'elm.json' saved [643]
```

That will probably force us to mirror at least all dependency metadata (and maybe packages themselves as well?)

**Comment by hololeap** [comment] 2022-12-19 00:34
Closing, as `dev-lang/elm-reactor` and `dev-lang/elm-compiler` are now removed from the overlay.

See:
- 714c5b6310af2350e3bd57dc156853824c118311
- https://github.com/gentoo-haskell/gentoo-haskell/pull/1330
- https://github.com/gentoo-haskell/gentoo-haskell/blob/1b5fa9a5bd29aa252d513d105dc0ff01a4d6370b/profiles/package.mask#L1-L14

**Closed by hololeap** 2022-12-19 00:34 UTC
