### ISSUE TITLE
[xmobar] Unable to toggle visibility of xmobar by dbus after xmonad --recompile; xmonad --restart

### ISSUE THREAD

**Issue by hereGittyGitty** [gentoo-haskell/gentoo-haskell#1284] opened 2022-05-15 13:14 UTC
Hi,
with `x11-misc/xmobar-0.43`, I am unable to toggle the visibility of `xmobar` after `xmonad --recompile; xmonad --restart` when using
```
dbus-send --session --dest=org.Xmobar.Control --type=method_call '/org/Xmobar/Control' org.Xmobar.Control.SendSignal "string:Toggle 0"
```
It works before restarting `xmonad`.

It works fine with `x11-misc/xmobar-0.41` before and after restarting `xmonad`.

Thanks and have a nice day :)

**Comment by hololeap** [comment] 2022-05-15 18:00
This could be an error in the ebuild added in https://github.com/gentoo-haskell/gentoo-haskell/commit/62deda8445323600a5f1a141f5ae478e99ac8056, but it seems more likely to be an upstream bug. There is very little difference between the `0.41` ebuild and the new one.

I wonder if any of this has to do with what you are experiencing?
- https://github.com/jaor/xmobar/releases/tag/0.43
- https://github.com/jaor/xmobar/issues/499
- https://github.com/jaor/xmobar/pull/500
- https://github.com/jaor/xmobar/commit/082ef98c1c265ad927b728402d8803a86bbbaeef

**Comment by hereGittyGitty** [comment] 2022-05-15 20:30
Hey,
thx for looking into this. The upstream changes you suggested look promising. Meanwhile, I tried to install the _live ebuild_ of `xmonad` to check for fixes, but I had no luck in doing so. Let's see if your _links_ in the corresponding upstream issues will shed some light into this. If you need any more information or action on my side, just ask for it.

Have a good one

**Comment by hololeap** [comment] 2022-05-15 22:43
@hereGittyGitty 

[I added `xmobar-0.42`](https://github.com/gentoo-haskell/gentoo-haskell/commit/d04129b8e8792934a49a0e69bc307355a5f0ac71), so you can try that version to confirm the issue is specific to version `0.43`.

> Meanwhile, I tried to install the _live ebuild_ of `xmonad` to check for fixes, but I had no luck in doing so.

It says on the `xmobar` project page that it is actually _not_ dependent on `xmonad`, so this shouldn't have any affect. If you mistyped, and actually meant the live ebuild of _`xmobar`_, I don't think that would help either, since there are only a few new commits since the release of version `0.43`. (It also looks like that ebuild has not been updated in a long time.)

**Comment by hereGittyGitty** [comment] 2022-05-16 08:32
@hololeap
Yes, that was a mistyping in my previous message: I meant `xmobar` (fixed that in the previous message). I just tested `xmobar-0.42` and experienced the same problematic behavior as with `xmobar-0.43`.

**Comment by solpeth** [comment] 2022-05-16 21:21
If you haven't already, I'd send this upstream to xmobar. They may be able to determine if some of their code changes (or xmonad's) could be causing this, as I can't see how our ebuild is to blame at this stage.

**Comment by hereGittyGitty** [comment] 2022-05-17 07:30
> If you haven't already, I'd send this upstream to xmobar. They may be able to determine if some of their code changes (or xmonad's) could be causing this, as I can't see how our ebuild is to blame at this stage.

Yes you may do so. Thank you

**Comment by hereGittyGitty** [comment] 2022-05-19 18:07
Did that:
#https://github.com/jaor/xmobar/issues/632#issue-1242130801

**Comment by hololeap** [comment] 2022-05-20 02:36
@hereGittyGitty

I'm going to close this. Go ahead and re-open it if you need to.

**Closed by hololeap** 2022-05-20 02:36 UTC
