### ISSUE TITLE
`cabal_chdeps()` should support `patsub_replacement`

### ISSUE THREAD

**Issue by open-antux** [gentoo-haskell/gentoo-haskell#1363] opened 2022-11-26 11:58 UTC
Hi everyone,

during the upgrade, I had the following error while compiling `dev-haskell/ghc-paths-0.1.0.12-r3`:
```ebuild
 * Package:    dev-haskell/ghc-paths-0.1.0.12-r3:0/0.1.0.12
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc hscolour kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking ghc-paths-0.1.0.12.tar.gz to /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work
>>> Unpacking ghc-paths-0.1.0.12-rev4.cabal to /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work
unpack ghc-paths-0.1.0.12-rev4.cabal: file format not recognized. Ignoring.
>>> Source unpacked in /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work
>>> Preparing source in /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12 ...
removed '/var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12/Setup.hs'
 * Creating 'Setup.hs' for 'Simple' build type.
 * CHDEP: 'Cabal >= 1.6 && <3.1' -> 'Cabal >= 1.6 && <3.5'
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12 ...
 * Using cabal-3.6.3.0.
/usr/bin/ghc -hide-all-packages -package Cabal -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml --make /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12/Setup.hs -j6 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12/Setup.hs, /var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12/Setup.o )
Linking setup ...
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=ghc-paths-0.1.0.12/ghc-9.0.2 --datadir=/usr/share/ --datasubdir=ghc-paths-0.1.0.12/ghc-9.0.2 --ghc-options=-j6 +RTS -A256M -qb0 -RTS --with-ar=x86_64-pc-linux-gnu-ar --ghc-option=-optc-march=native --ghc-option=-optc-O2 --ghc-option=-optc-pipe --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --disable-executable-stripping --docdir=/usr/share/doc/ghc-paths-0.1.0.12-r3 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping
Using Parsec parser
Warning: ghc-paths.cabal:16:55:
unexpected 'C'
expecting space, "&&", white space, "||", comma or end of input

setup: Failed parsing "./ghc-paths.cabal".

 * ghc-pkg check: 'checking for other broken packages:'
There are problems in package pandoc-2.19.2:
  Warning: haddock-interfaces: /usr/share/doc/pandoc-2.19.2/html/pandoc.haddock doesn't exist or isn't a file
  Warning: haddock-html: /usr/share/doc/pandoc-2.19.2/html doesn't exist or isn't a directory
  dependency "JuicyPixels-3.3.7-HwuGTnpg4dM1coBeJbKG2K" doesn't exist
  dependency "attoparsec-0.14.4-7zB3pKxEnAuAUcD4YMiVmn" doesn't exist
  dependency "base64-0.4.2.4-CkSAYMUidsA7U6qcnz4Uff" doesn't exist
  dependency "case-insensitive-1.2.1.0-2jEHhoFCxoA7RSfoe4YHcJ" doesn't exist
  dependency "commonmark-extensions-0.2.3.2-1eqyiNFhwah3E4SUffNGEz" doesn't exist
  dependency "connection-0.3.1-31fWuftn5uAD8fHwju87Xr" doesn't exist
  dependency "http-client-0.7.11-5JtAchyZBAL6T4IYvMlt8S" doesn't exist
  dependency "http-client-tls-0.3.6.1-AUMw8dsjuPh2V3eXQQEWxy" doesn't exist
  dependency "http-types-0.12.3-LS2UyjPt3rN2lG4MyMNYQh" doesn't exist
  dependency "network-3.1.2.6-94FPWuEVAlMFCgZ9XDxjt6" doesn't exist
  dependency "network-uri-2.6.4.1-LGqNQI3sHlGE7AMWq5Lzlx" doesn't exist
  dependency "scientific-0.3.7.0-Jsg3cNnv1Wm5fibWMVpvZm" doesn't exist
  dependency "split-0.2.3.4-8X1jE248hsmCErmcz78K1t" doesn't exist
  dependency "unicode-collation-0.1.3.1-GXOV0v9g9vc7E8mCG1QEwT" doesn't exist
  dependency "wai-3.2.3-B4Ynyled73WKfIVuEqQLHH" doesn't exist
There are problems in package commonmark-pandoc-0.2.1.2:
  dependency "commonmark-extensions-0.2.3.2-1eqyiNFhwah3E4SUffNGEz" doesn't exist
 * Detected broken packages: pandoc-2.19.2 commonmark-pandoc-0.2.1.2 wai-app-static-3.1.7.2 ipynb-0.2 http-date-0.0.11 attoparsec-iso8601-1.0.2.1 path-0.9.2 path-io-1.6.3 xml-html-qq-0.1.0.1 xml-conduit-1.9.1.1 doctemplates-0.10.0.2 warp-3.3.21 http-api-data-0.4.3 servant-server-0.19.2 aeson-2.0.3.0 hlint-3.4.1 wai-extra-3.1.12.1 xmobar-0.44.1 warp-tls-3.2.12 skylighting-core-0.13.1.1 haskell-gi-0.26.1 hslua-aeson-2.2.1 shakespeare-2.0.30 citeproc-0.8.0.2 parsers-0.12.10 html-conduit-1.3.2.1 yaml-0.11.8.0 http-conduit-2.3.8 termonad-4.2.0.1 servant-0.19.1 dbus-1.2.22 texmath-0.12.5.1 aeson-pretty-0.8.9 conduit-extra-1.3.6 inline-c-0.9.1.6 gi-harfbuzz-0.0.6 gi-atk-2.0.24 pandoc-types-1.22.2 gi-glib-2.0.26 skylighting-0.13.1.1 skylighting-format-blaze-html-0.1.1 pandoc-lua-marshal-0.1.7 deriving-aeson-0.2.8 skylighting-format-latex-0.1 gi-gmodule-2.0.2 gi-gtk-3.0.38 heterocephalus-1.0.5.6 gi-gobject-2.0.27 gi-gdk-3.0.25 gi-gio-2.0.29 gi-vte-2.91.29 hslua-module-doclayout-1.0.4 gi-cairo-1.0.26 gi-gdkpixbuf-2.0.28 hslua-2.2.1 gi-freetype2-2.0.1 skylighting-format-ansi-0.1 gi-pango-1.0.26
 * ERROR: dev-haskell/ghc-paths-0.1.0.12-r3::haskell failed (configure phase):
 *   //==-- Please, run 'haskell-updater' to fix broken packages --==//
 * 
 * Call stack:
 *     ebuild.sh, line  122:  Called src_configure
 *   environment, line 1899:  Called haskell-cabal_src_configure
 *   environment, line 1567:  Called cabal-configure
 *   environment, line  552:  Called cabal-show-brokens-and-die 'setup configure failed'
 *   environment, line  675:  Called cabal-show-brokens
 *   environment, line  671:  Called cabal-die-if-nonempty 'broken' 'pandoc-2.19.2' 'commonmark-pandoc-0.2.1.2' 'wai-app-static-3.1.7.2' 'ipynb-0.2' 'http-date-0.0.11' 'attoparsec-iso8601-1.0.2.1' 'path-0.9.2' 'path-io-1.6.3' 'xml-html-qq-0.1.0.1' 'xml-conduit-1.9.1.1' 'doctemplates-0.10.0.2' 'warp-3.3.21' 'http-api-data-0.4.3' 'servant-server-0.19.2' 'aeson-2.0.3.0' 'hlint-3.4.1' 'wai-extra-3.1.12.1' 'xmobar-0.44.1' 'warp-tls-3.2.12' 'skylighting-core-0.13.1.1' 'haskell-gi-0.26.1' 'hslua-aeson-2.2.1' 'shakespeare-2.0.30' 'citeproc-0.8.0.2' 'parsers-0.12.10' 'html-conduit-1.3.2.1' 'yaml-0.11.8.0' 'http-conduit-2.3.8' 'termonad-4.2.0.1' 'servant-0.19.1' 'dbus-1.2.22' 'texmath-0.12.5.1' 'aeson-pretty-0.8.9' 'conduit-extra-1.3.6' 'inline-c-0.9.1.6' 'gi-harfbuzz-0.0.6' 'gi-atk-2.0.24' 'pandoc-types-1.22.2' 'gi-glib-2.0.26' 'skylighting-0.13.1.1' 'skylighting-format-blaze-html-0.1.1' 'pandoc-lua-marshal-0.1.7' 'deriving-aeson-0.2.8' 'skylighting-format-latex-0.1' 'gi-gmodule-2.0.2' 'gi-gtk-3.0.38' 'heterocephalus-1.0.5.6' 'gi-gobject-2.0.27' 'gi-gdk-3.0.25' 'gi-gio-2.0.29' 'gi-vte-2.91.29' 'hslua-module-doclayout-1.0.4' 'gi-cairo-1.0.26' 'gi-gdkpixbuf-2.0.28' 'hslua-2.2.1' 'gi-freetype2-2.0.1' 'skylighting-format-ansi-0.1' 'gi-pango-1.0.26'
 *   environment, line  573:  Called die
 * The specific snippet of code:
 *       die "//==-- Please, run 'haskell-updater' to fix ${breakage_type} packages --==//"
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/ghc-paths-0.1.0.12-r3::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/ghc-paths-0.1.0.12-r3::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12'
 * S: '/var/tmp/portage/dev-haskell/ghc-paths-0.1.0.12-r3/work/ghc-paths-0.1.0.12'
```
I've find the cause of the problem, in the `ghc-paths.cabal` there's a syntax error:
```cabal
custom-setup
        setup-depends: base >= 3 && < 5, Cabal >= 1.6 Cabal >= 1.6 && <3.1Cabal >= 1.6 && <3.1 <3.5, directory
```
I think that should be
```cabal
custom-setup
        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.5, directory
```

**Comment by hololeap** [comment] 2022-11-26 16:15
I am not able to reproduce this. The original `.cabal` file has the block:

* [`ghc-paths.cabal`](https://hackage.haskell.org/package/ghc-paths-0.1.0.12/revision/0.cabal)
  ```cabal
  custom-setup
          setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.1, directory
  ```

However, this is changed with [`cabal_chdeps()`](https://github.com/gentoo-haskell/gentoo-haskell/blob/9717dc2f5e05ce445237165ed4cb076d451f00ad/eclass/haskell-cabal.eclass#L865-L911), which is supposed to change it to:

```cabal
custom-setup
        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.5, directory
```

https://github.com/gentoo-haskell/gentoo-haskell/blob/9717dc2f5e05ce445237165ed4cb076d451f00ad/dev-haskell/ghc-paths/ghc-paths-0.1.0.12-r3.ebuild#L32-L33

(This works correctly on my system)

**Comment by hololeap** [comment] 2022-11-26 16:33
It looks like it's doing some [bash parameter substitution](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) in `cabal_chdeps()`:

https://github.com/gentoo-haskell/gentoo-haskell/blob/9717dc2f5e05ce445237165ed4cb076d451f00ad/eclass/haskell-cabal.eclass#L891-L895

Try running this to see if it will reproduce the bug in your shell:

```bash
line="        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.1, directory"
from_pat='Cabal >= 1.6 && <3.1'
to_str='Cabal >= 1.6 && <3.5'
echo "\"${line//${from_pat}/${to_str}}\""
```

In my shell, this outputs:

```
"        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.5, directory"
```

**Comment by open-antux** [comment] 2022-11-27 10:15
Hi,

thanks for the response. This is the output of the commands:
```bash
gentoo ~ # line="        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.1, directory"
gentoo ~ # from_pat='Cabal >= 1.6 && <3.1'
gentoo ~ # to_str='Cabal >= 1.6 && <3.5'
gentoo ~ # echo "\"${line//${from_pat}/${to_str}}\""
"        setup-depends: base >= 3 && < 5, Cabal >= 1.6 Cabal >= 1.6 && <3.1Cabal >= 1.6 && <3.1 <3.5, directory"
```
After some testing, I noticed that the issue comes when bash tries to substitute the `&&`, in fact, if I try to use them as character `\&` the problem is solved:
```bash
gentoo ~ # line="        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.1, directory"
gentoo ~ # from_pat='Cabal >= 1.6 && <3.1'
gentoo ~ # to_str='Cabal >= 1.6 \&\& <3.5'
gentoo ~ # echo "\"${line//${from_pat}/${to_str}}\""
"        setup-depends: base >= 3 && < 5, Cabal >= 1.6 && <3.5, directory"
```
I think that bash use `&` as a placeholder for in the pattern to substitude
```bash
gentoo ~ # line="Hi my name is Antonio && open-antux"
gentoo ~ # echo "${line//Antonio && open-antux/Foo &}" # Foo &  = Foo Antonio && open-antux
Hi my name is Foo Antonio && open-antux
gentoo ~ # echo "${line//Antonio && open-antux/Foo & Shakespeare}" # Foo & Shakespeare = Foo Antonio && open-antux Shakespeare
gentoo ~ # echo "${line//Antonio && open-antux/Foo &&}" # Foo && =  Foo Antonio && open-antuxAntonio && open-antux
Hi my name is Foo Antonio && open-antuxAntonio && open-antux
```
Maybe a better solution could be `to_str=$(sed -E 's/(\&|\|)/\\\1/g' <<< 'Cabal >= 1.6 && <3.5')` in order to prevent bash to use operator like `&` or `|` as a placeholder or something else instead of a character.

**Comment by hololeap** [comment] 2022-11-27 18:25
From [the bash reference manual](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html): 

> If the `patsub_replacement` shell option is enabled using `shopt`, any unquoted instances of '`&`' in _string_ are replaced with the matching portion of _pattern_. This is intended to duplicate a common `sed` idiom.

So this should explain the discrepancy on your system.

**Comment by hololeap** [comment] 2022-11-27 19:12
See if it works for you now that I pushed https://github.com/gentoo-haskell/gentoo-haskell/commit/89949486a9c3619bfc85d1ef9f8319843ca501b6.

**Comment by hololeap** [comment] 2022-11-27 19:14
Oh, I also pushed an update to `dev-haskell/ghc-paths` (https://github.com/gentoo-haskell/gentoo-haskell/commit/cf1bef9e004e24f23ac954ef3aeb920a10a71295) which removed `cabal_chdeps` (it was unneeded thanks to the upstream Hackage revision), so you won't be able to test using that.

**Comment by hololeap** [comment] 2022-11-27 19:18
You could test with `dev-haskell/rest-rewrite`:

https://github.com/gentoo-haskell/gentoo-haskell/blob/cf1bef9e004e24f23ac954ef3aeb920a10a71295/dev-haskell/rest-rewrite/rest-rewrite-0.4.0.ebuild#L18-L20

**Comment by hololeap** [comment] 2022-11-28 16:53
Good. Closing, but feel free to reopen if you need to.

**Closed by hololeap** 2022-11-28 16:53 UTC

**Comment by hololeap** [comment] 2022-11-30 01:33
https://github.com/gentoo/portage/pull/944
