### ISSUE TITLE
dev-lang/elm-reactor-0.18.0 failed compile

### ISSUE THREAD

**Issue by Sheridan** [gentoo-haskell/gentoo-haskell#608] opened 2017-04-22 19:07 UTC
```
>>> Emerging (1 of 2) dev-lang/elm-reactor-0.18.0::haskell
 * elm-reactor-0.18.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                      [ ok ]
>>> Unpacking source...
>>> Unpacking elm-reactor-0.18.0.tar.gz to /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work
>>> Source unpacked in /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work
>>> Preparing source in /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0 ...
>>> Source prepared.
>>> Configuring source in /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0 ...
 * No Setup.lhs or Setup.hs found. Either add Setup.hs to package or call cabal-mksetup from ebuild
 * Creating 'Setup.hs' for 'Simple' build type.
 * Using cabal-1.22.8.0.
 * Prepending /usr/lib64/ghc-7.10.3 to LD_LIBRARY_PATH
/usr/bin/ghc -package Cabal-1.22.8.0 --make /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0/Setup.hs -j8 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0/Setup.hs, /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0/Setup.o )
Linking setup ...
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=elm-reactor-0.18.0/ghc-7.10.3 --datadir=/usr/share/ --datasubdir=elm-reactor-0.18.0/ghc-7.10.3 --ghc-options=-j8 +RTS -A256M -qb0 -RTS --with-ar=x86_64-pc-linux-gnu-ar --ghc-option=-optc-march=native --ghc-option=-optc-O2 --ghc-option=-optc-pipe --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --disable-executable-stripping --docdir=/usr/share/doc/elm-reactor-0.18.0 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping
Configuring elm-reactor-0.18...
Dependency aeson >=0.7: using aeson-1.0.2.1
Dependency base >=4.2 && <5: using base-4.8.2.0
Dependency blaze-html -any: using blaze-html-0.8.1.1
Dependency blaze-markup -any: using blaze-markup-0.7.0.3
Dependency bytestring -any: using bytestring-0.10.6.0
Dependency cmdargs -any: using cmdargs-0.10.7
Dependency containers -any: using containers-0.5.6.2
Dependency directory >=1.2: using directory-1.2.2.0
Dependency elm-compiler ==0.18: using elm-compiler-0.18
Dependency elm-package -any: using elm-package-0.18
Dependency file-embed -any: using file-embed-0.0.7
Dependency filepath -any: using filepath-1.4.0.0
Dependency fsnotify >=0.2: using fsnotify-0.2.1
Dependency mtl -any: using mtl-2.2.1
Dependency process -any: using process-1.2.3.0
Dependency snap-core -any: using snap-core-1.0.2.0
Dependency snap-server -any: using snap-server-1.0.1.1
Dependency template-haskell -any: using template-haskell-2.10.0.0
Dependency text -any: using text-1.2.2.1
Dependency time -any: using time-1.5.0.1
Dependency transformers -any: using transformers-0.4.3.0
Dependency unordered-containers -any: using unordered-containers-0.2.7.0
Dependency utf8-string -any: using utf8-string-0.3.8
Dependency websockets ==0.9.*: using websockets-0.9.7.0
Dependency websockets-snap >=0.8.2.1: using websockets-snap-0.10.2.1
Using Cabal-1.22.8.0 compiled by ghc-7.10
Using compiler: ghc-7.10.3
Using install prefix: /usr
Binaries installed in: /usr/bin
Libraries installed in: /usr/lib64/elm-reactor-0.18.0/ghc-7.10.3
Private binaries installed in: /usr/libexec
Data files installed in: /usr/share/elm-reactor-0.18.0/ghc-7.10.3
Documentation installed in: /usr/share/doc/elm-reactor-0.18.0
Configuration files installed in: /etc
No alex found
Using ar given by user at: /usr/bin/x86_64-pc-linux-gnu-ar
No c2hs found
No cpphs found
Using gcc version 4.9.4 found on system at: /usr/bin/gcc
Using ghc version 7.10.3 given by user at: /usr/bin/ghc
Using ghc-pkg version 7.10.3 given by user at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
No haddock found
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.28 found on system at: /usr/bin/pkg-config
Using strip version 2.25 found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
No uhc found
>>> Source configured.
>>> Compiling source in /data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0 ...
./setup build
Building elm-reactor-0.18...
Preprocessing executable 'elm-reactor' for elm-reactor-0.18...
[1 of 8] Compiling StaticFiles.Build ( src/backend/StaticFiles/Build.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles/Build.dyn_o )
[2 of 8] Compiling Socket           ( src/backend/Socket.hs, dist/build/elm-reactor/elm-reactor-tmp/Socket.dyn_o )

src/backend/Socket.hs:15:11: Warning:
    Defined but not used: `watchedFile'
[3 of 8] Compiling Generate.Help    ( src/backend/Generate/Help.hs, dist/build/elm-reactor/elm-reactor-tmp/Generate/Help.dyn_o )
[4 of 8] Compiling StaticFiles      ( src/backend/StaticFiles.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles.dyn_o )
Failed to build src/pages/Errors.elm





src/backend/StaticFiles.hs:50:5:
    Exception when trying to run compile-time code:
      ExitFailure 1
    Code: (=<<)
            bsToExp runIO (Build.compile ("src" </> "pages" </> "Errors.elm"))
    In the splice:
      $(bsToExp
        =<< runIO (Build.compile ("src" </> "pages" </> "Errors.elm")))
 * ERROR: dev-lang/elm-reactor-0.18.0::haskell failed (compile phase):
 *   setup build failed
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 2932:  Called haskell-cabal_src_compile
 *   environment, line 2039:  Called cabal_src_compile
 *   environment, line  737:  Called cabal-build
 *   environment, line  501:  Called die
 * The specific snippet of code:
 *       ./setup "$@" || die "setup build failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/elm-reactor-0.18.0::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/elm-reactor-0.18.0::haskell'`.
 * The complete build log is located at '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/temp/build.log'.
 * The ebuild environment file is located at '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/temp/environment'.
 * Working directory: '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0'
 * S: '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0'

>>> Failed to emerge dev-lang/elm-reactor-0.18.0, Log file:

>>>  '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/temp/build.log'

 * Messages for package dev-lang/elm-reactor-0.18.0:

 * Creating 'Setup.hs' for 'Simple' build type.
 * ERROR: dev-lang/elm-reactor-0.18.0::haskell failed (compile phase):
 *   setup build failed
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 2932:  Called haskell-cabal_src_compile
 *   environment, line 2039:  Called cabal_src_compile
 *   environment, line  737:  Called cabal-build
 *   environment, line  501:  Called die
 * The specific snippet of code:
 *       ./setup "$@" || die "setup build failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/elm-reactor-0.18.0::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/elm-reactor-0.18.0::haskell'`.
 * The complete build log is located at '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/temp/build.log'.
 * The ebuild environment file is located at '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/temp/environment'.
 * Working directory: '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0'
 * S: '/data/var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0'
spc / # 


spc / # emerge --info
Portage 2.3.3 (python 3.4.6-final-0, default/linux/amd64/13.0/systemd, gcc-4.9.4, glibc-2.23-r3, 4.9.6-gentoo-r1.Sheridan.home x86_64)
=================================================================
System uname: Linux-4.9.6-gentoo-r1.Sheridan.home-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.3
KiB Mem:    16397296 total,   5208356 free
KiB Swap:   33554428 total,  33554268 free
Timestamp of repository gentoo: Wed, 12 Apr 2017 21:00:01 +0000
sh bash 4.3_p48-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p48-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.3_rc4::gentoo
dev-lang/python:          2.7.13::gentoo, 3.4.6::gentoo, 3.5.2::gentoo
dev-util/cmake:           3.7.2::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.23.2::gentoo
sys-apps/sandbox:         2.10-r3::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.12.6::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo, 2.26.1::gentoo
sys-devel/gcc:            4.8.5::gentoo, 4.9.4::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r3::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

tls
    location: /home/sheridan/development/github/timelapse/gentoo
    sync-type: git
    sync-uri: https://github.com/Sheridan/timelapse
    masters: gentoo

fkmclane
    location: /var/lib/layman/fkmclane
    masters: gentoo
    priority: 50

haskell
    location: /var/lib/layman/haskell
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

qt
    location: /var/lib/layman/qt
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

sunrise
    location: /var/lib/layman/sunrise
    masters: gentoo
    priority: 50

Installed sets: @qt5-addons, @qt5-essentials
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.6/ext-active/ /etc/php/apache2-php7.0/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cgi-php7.0/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/php/cli-php7.0/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/data/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirror.yandex.ru/gentoo-distfiles/"
LANG="C"
LC_ALL="C"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j8"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X aac aalib acl alsa amd64 apng applet bash-completion berkdb bindist bluetooth bzip2 c++11 cairo cdda cddb cli corefonts cracklib crypt cuda cue cups curl cxx dbus djvu dri efi egl equalizer exif ffmpeg flac fontconfig fortran ftp gdbm gif git gnome-keyring gstreamer gtk gtk3 gtkstyle gzip http iconv icu id3tag ipv6 ithreads javafx jpeg jpeg2k lame ldap libcaca libkms libnotify lm_sensors lua man matroska md5sum mdadm midi minizip mod modplug modules mp3 mpeg mplayer multilib natspec ncurses nls nptl nsplugin ogg opengl openmp pam pcre pcre16 pcre32 pdf perl png policykit postscript pulseaudio python qml qt qt5 rar readline rtmp rtsp samba sasl savedconfig sdl seccomp session skins smp spell spice sqlite ssh ssl startup-notification svg systemd tcpd terminus threads tiff truetype twolame udev udisks unicode usb uvm v4l vala vdpau visualizer vlc vnc vorbis wayland webkit x264 x265 xattr xcb xine xinerama xkb xml xmp xrandr xvid zip zlib zsh-completion" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 ssse3 sse4_1 sse4_2 sse4a aes avx fma3 fma4" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput keyboard mouse" KERNEL="linux" L10N="ru en" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="ru en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7" PYTHON_SINGLE_TARGET="python3_4" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby21" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON
```

**Comment by trofi** [comment] 2017-04-22 19:39
TH code tries to run roughly the following shell command:
```
$ LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js
$ echo $?
```

What does it output for you if you run it manually from emerge's working directory?

**Comment by Sheridan** [comment] 2017-04-22 20:20
```spc elm-reactor-0.18.0 # LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js
Starting downloads...

  [ok] elm-lang/svg 2.0.0
  [ok] elm-lang/virtual-dom 2.0.4
  [ok] evancz/elm-markdown 3.0.2
  [ok] elm-lang/html 2.0.0

  [ok] elm-lang/core 5.1.1
Packages configured successfully!
[=                                                 ] - 1 / 44[1]    26179 segmentation fault  LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js
spc elm-reactor-0.18.0 # echo $?
139
```

**Comment by trofi** [comment] 2017-04-22 22:47
Ugh. SIGSEGv looks bad. Do you have a backtrace or something that hints at why SIGSEGV happens?

**Comment by Sheridan** [comment] 2017-04-22 23:13
I can show you strace output...
```
spc elm-reactor-0.18.0 # LANG=C strace elm-make --yes src/pages/Errors.elm --output=foo.js > strace.out 2>&1
[1]    13165 segmentation fault  LANG=C strace elm-make --yes src/pages/Errors.elm --output=foo.js > strace.out
```
It causes suspicion of too many "No such file or directory" at the end.

[strace.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/949354/strace.txt)

upd.
Ghm...
I ran it two times in a row and:
```
spc elm-reactor-0.18.0 # LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js         
Starting downloads...

  [ok] elm-lang/virtual-dom 2.0.4
  [ok] elm-lang/svg 2.0.0
  [ok] elm-lang/html 2.0.0
  [ok] evancz/elm-markdown 3.0.2
  
[ok] elm-lang/core 5.1.1
Packages configured successfully!
[=====                                             ] - 5 / 44[1]    14955 segmentation fault  LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js
spc elm-reactor-0.18.0 # LANG=C elm-make --yes src/pages/Errors.elm --output=foo.js 
Success! Compiled 39 modules.                                       
Successfully generated foo.js
spc elm-reactor-0.18.0 # 
```

**Comment by trofi** [comment] 2017-04-23 21:11
Aha. I've not managed to reproduce failure on my machine yet.
It looks like crash happens after a bunch of garbage collection cycles.

My wild suspiction is on `ghc-7.10.3` (or one of libraries) to call finalizers improperly.

Did you by chance try `ghc-8.0.2`?

**Comment by graaff** [comment] 2017-05-12 07:13
I'm seeing the same issue (including the SIGSEGV). I'll try ghc-8.0.2 this weekend to see if that helps.

**Comment by graaff** [comment] 2017-05-14 09:35
I've just updated to ghc-8.0.2 and updated everything with haskell-updater. Now elm-reactor builds fine and works as expected.

**Comment by trofi** [comment] 2017-05-17 20:31
I still don't know why exactly ghc-7.10 causes SIGSEGVs. My hunch is that `ghc-8.0.2`
fixed a code generation bug. I've raised minimal dependency on `elm-reactor` up to `8.0.2`.

**Comment by graaff** [comment] 2018-04-19 19:51
I'm seeing this again with ghc 8.0.2 :-(

It looks to be inconsistent. I get clean runs sometimes, but mostly segfaults. The segfaults happen at different locations in the process. I'm using the elm-make snippet to test it directly. I haven't seen a segfault without LANG=C.

Using gdb on the core file that is generated shows:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000369ecf2227c in aes_encrypt_cbc () from /usr/lib64/x86_64-linux-ghc-8.0.2/libHScipher-aes-0.2.5-CO5UsXpQMUH6HHypbGA6Vs-ghc8.0.2.so
[Current thread is 1 (Thread 0x269d36d6700 (LWP 22520))]
(gdb) bt
#0  0x00000369ecf2227c in aes_encrypt_cbc () from /usr/lib64/x86_64-linux-ghc-8.0.2/libHScipher-aes-0.2.5-CO5UsXpQMUH6HHypbGA6Vs-ghc8.0.2.so
#1  0x00000369ecf1ca2d in ?? () from /usr/lib64/x86_64-linux-ghc-8.0.2/libHScipher-aes-0.2.5-CO5UsXpQMUH6HHypbGA6Vs-ghc8.0.2.so
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()

**Comment by trofi** [comment] 2018-05-12 18:06
Oh, interesting. Wonder if it could be a bug in C code of `cipher-aes`. If this still pops up for you can you build it with debugging symbols and grab a backtrace again?

And post your `emerge --info cipher-aes`. I'll try to replicate locally.

**Comment by graaff** [comment] 2018-07-11 05:54
I've just upgraded one of the problematic systems to a newer versions of tls using the following keywords, and elm-reactor now emerges without issues.

~~~
~dev-haskell/tls-1.3.9
~dev-haskell/x509-1.6.5
~dev-haskell/x509-store-1.6.2
~dev-haskell/x509-validation-1.6.5
~dev-haskell/x509-system-1.6.3
~dev-haskell/asn1-parse-0.9.4
~dev-haskell/asn1-types-0.3.2
~dev-haskell/connection-0.2.5
~~~

**Comment by trofi** [comment] 2018-08-05 20:53
Let's close it then.

Thanks for the update!

**Closed by trofi** 2018-08-05 20:53 UTC
